### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Timass60** [mhdimo/Zellia80-HE#1]
- [x] Re-route MUX outputs
- [ ] \(Optional) Re-route USB
- [ ] Finish power supply
- [ ] Reset circuit
- [ ] Route SWD

**Comment by mhdimo** [comment]
perhaps it is better splitting this issue in more than one to get more in control and go in with small steps
